services:
  db:
    image: mysql:8.0
    container_name: talentbridge_db
    environment:
      MYSQL_ROOT_PASSWORD: hello1234
      MYSQL_DATABASE: TalentBridgeDB
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/TalentBridge_Testdata.sql:/docker-entrypoint-initdb.d/TalentBridge_Testdata.sql

  app:
    build:
      context: ./API
    container_name: talentbridge_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: hello1234
      DB_NAME: TalentBridgeDB
    depends_on:
      - db

volumes:
  db_data: